import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateDashboardPDF = ({
  students,
  totalMoney,
  totalExpenses,
  totalMeal,
  expensePerMeal,
}) => {
  if (!students || students.length === 0) {
    alert("No student data to export!");
    return;
  }

  const doc = new jsPDF({ orientation: "landscape" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // ===== HEADER =====
  doc.setFillColor(22, 160, 133);
  doc.rect(0, 0, pageWidth, 25, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text("Monthly Dashboard Report", 14, 17);

  doc.setFontSize(10);
  doc.setTextColor(230);
  const today = new Date();
  const formattedDate = `${String(today.getDate()).padStart(2, "0")}/${String(
    today.getMonth() + 1,
  ).padStart(2, "0")}/${today.getFullYear()}`;
  doc.text(`Generated on: ${formattedDate}`, pageWidth - 60, 17);

  // ===== SUMMARY BOX =====
  const margin = 14;
  const boxWidth = pageWidth - 2 * margin;
  const boxY = 30;
  const boxHeight = 18;

  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, boxY, boxWidth, boxHeight, 3, 3, "F");

  const summaryItems = [
    {
      label: "Total Money",
      value: totalMoney.toLocaleString(),
      color: [0, 102, 51],
    },
    {
      label: "Total Expenses",
      value: totalExpenses.toLocaleString(),
      color: [204, 0, 0],
    },
    {
      label: "Total Meal",
      value: totalMeal.toLocaleString(),
      color: [102, 0, 204],
    },
  ];

  const spacing = boxWidth / summaryItems.length;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");

  summaryItems.forEach((item, index) => {
    const x = margin + spacing * index + 4;
    doc.setTextColor(...item.color);
    doc.text(`${item.label}: ${item.value}`, x, boxY + 12);
  });

  doc.setTextColor(120, 130, 210);
  doc.text(
    `Per Meal Expense: ${expensePerMeal.toFixed(2)}`,
    pageWidth - margin - 2,
    boxY + 12,
    { align: "right" },
  );

  // ===== TABLE =====
  const tableColumn = [
    "SL",
    "Name",
    "Total Money",
    "Total Meal",
    "Expenses",
    "Remaining Balance",
    "Status",
  ];

  const tableRows = students.map((student, index) => {
    let status = "-";

    if (student.balance > 0) status = "Receive";
    if (student.balance < 0) status = "Pay";

    return [
      index + 1,
      student.name,
      student.totalMoney.toLocaleString(),
      student.totalMill.toLocaleString(),
      student.expense.toFixed(2),
      student.balance.toFixed(2),
      status,
    ];
  });

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: boxY + boxHeight + 7,

    margin: {
      bottom: 25,
    },

    didParseCell: function (data) {
      // Remaining Balance column
      if (data.column.index === 5 && data.cell.section === "body") {
        const value = Number(data.cell.raw);

        if (value > 0) {
          data.cell.styles.textColor = [0, 128, 0];
          data.cell.styles.fontStyle = "bold";
        }

        if (value < 0) {
          data.cell.styles.textColor = [255, 0, 0];
          data.cell.styles.fontStyle = "bold";
        }
      }

      // Status column
      if (data.column.index === 6 && data.cell.section === "body") {
        const status = data.cell.raw;

        if (status === "Receive") {
          data.cell.styles.textColor = [0, 128, 0];
          data.cell.styles.fontStyle = "bold";
        }

        if (status === "Pay") {
          data.cell.styles.textColor = [255, 0, 0];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },

    didDrawPage: function (data) {
      const pageCount = doc.internal.getNumberOfPages();
      const pageHeight = doc.internal.pageSize.height;
      const pageWidth = doc.internal.pageSize.width;

      doc.setDrawColor(200);
      doc.line(10, pageHeight - 20, pageWidth - 10, pageHeight - 20);

      doc.setFontSize(8);
      doc.setTextColor(0);
      doc.text("Prepared By:", 20, pageHeight - 10);
      doc.text("Verified By:", pageWidth / 2 + 20, pageHeight - 10);

      doc.line(45, pageHeight - 12, 110, pageHeight - 12);
      doc.line(
        pageWidth / 2 + 45,
        pageHeight - 10,
        pageWidth / 2 + 110,
        pageHeight - 10,
      );

      doc.setFontSize(6);
      doc.setTextColor(100);
      doc.text("(Name & Signature)", 60, pageHeight - 5);
      doc.text("(Name & Signature)", pageWidth / 2 + 65, pageHeight - 5);

      doc.setFontSize(4);
      doc.setTextColor(120);
      doc.text("Generated by Student Meal Manager", 14, pageHeight - 2);
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        pageWidth - 40,
        pageHeight - 2,
      );
    },
  });

  doc.save("student_dashboard_report.pdf");
};
